### PR TITLE
fixed overflowing by making the event expand down if hovered

### LINKED ISSUE #71: calendar component overflow
image

^^

dont know fix. maybe format date differently or add popup when hovering

### PR DESCRIPTION
**Pull request by Embretr**
tried to add some animations, but failed :/, im shure its possible but hard would likely require a rework of the calendar component.

### CODE REVIEW

File: src/components/ui/calendar/reservation-shard.tsx [hunk 1]
```diff
@@ -26,14 +31,71 @@ export default function ReservationShard({
...
+            ref={wrapperRef}
+            whileHover={{
+                height:
+                    innerInfoRef.current?.offsetHeight! >=
+                    wrapperRef.current?.offsetHeight!
+                        ? 'auto'
+                        : height,
+            }}
+            transition={{
+                duration: 0, //jævlig vanskelig å animate den her, 10 index poeng til den som klarer det (du kan kreve poengene hos mads)
```
Comment (frikkbol) [inline src/components/ui/calendar/reservation-shard.tsx:85]: watch me lolol

**Review by MindChirp — APPROVED** [review]
nice
